### ISSUE TITLE
Lua Script Error

### ISSUE THREAD

**Issue by TMPretox** [malucooo/otxserver-global#1]
Lua Script Error: [Action Interface]
data/actions/scripts/other/destroy.lua:onUse
data/actions/scripts/other/destroy.lua:2: attempt to call global 'onDestroyItem' (a nil value)
stack traceback:
        [C]: in function 'onDestroyItem'
        data/actions/scripts/other/destroy.lua:2: in function <data/actions/scripts/other/destroy.lua:1>

**Comment by malucooo** [comment]
fixed on last commit
