### ISSUE TITLE
Group_id dosn't exist

### ISSUE THREAD

**Issue by eduardolozano1993** [malucooo/Otxserver-Global#10]
When I try to login into any account I get the following message as shown in the next image.

http://imgur.com/a/qH0mV

I have tried to change the gorup_id between 1,2,3 but the error persist. I'm using the compiled version x64 on Windows.

**Comment by malucooo** [comment]
look ur group.xml file in folder data/xml/
and show me here

**Comment by eduardolozano1993** [comment]
My group.xml was empty for some reason.
