### ISSUE TITLE
Fix a nil value

### ISSUE THREAD

**Issue by Tetee11** [malucooo/otxserver-global#10]
When you try to destroy containers with weapons.

Lua Script Error: [Action Interface]
data/actions/scripts/scripts/other/destroy.lua:onUse
data/actions/scripts/other/destroy.lua:2: attempt to call global 'destroyItem' <a nil value>
stack traceback:
        [C]: in function 'destroyItem'
        data/actions/other/destroy.lua:2: in function <data/scripts/actions/other/destroy.lua:1>

change
`function DestroyItem(player, item, fromPosition, target, toPosition, isHotkey)`

for
`function destroyItem(player, item, fromPosition, target, toPosition, isHotkey)`

The problem here is the "D"`

**Comment by malucooo** [comment]
fixed!
