### ISSUE TITLE
Orc Berserk looks like NPC

### ISSUE THREAD

**Issue by newacc12** [malucooo/otxserver-global#11]
After I download the latest the berserkers look like npcs:

![Image](http://image.prntscr.com/image/c98985c1563048b093923e70ecf6959e.png)

**Comment by lamonato29** [comment]
they look like npc or they act like npc?

**Comment by newacc12** [comment]
@lamonato29 I'm sorry, they act like. You say Hi they answer and stop walking. Also they don't attack you

**Comment by Blingx** [comment]
Is it just the orc beserkers?

**Comment by jakksen** [comment]
My Orc berserkers is all normal

**Comment by newacc12** [comment]
@Blingx That I've found yes.
@jakksen Did you extract the latest map from world.zip ?

**Comment by jakksen** [comment]
Yes, if there was no change i use the same. I downloaded this about 7 days ago

**Comment by jakksen** [comment]
Did you do anything with your npc folder?

**Comment by newacc12** [comment]
@jakksen There has been an update to the map 4 days ago: https://github.com/malucooo/otxserver-global/commit/bdc1fd951f3eb0eadd7cac2a15d2f36b5de6761e 

dont forget it is to the zip file so you gotta extract. Im not saying this is the problem but I noticed it after I applied this commit. The only thing I have changes about the npcs is the delay when answering a player

**Comment by jakksen** [comment]
Im not having error, i just reply to the issue. All my monsters and npc's running fine.

**Comment by newacc12** [comment]
I was not having the error before I updated to the lastest version. My point is you might not be having it because you are not using the latest. Anyway thanks for the information. I will make sure again Im on the latest version and try again to confirm that this is a bug. I will update later

**Comment by malucooo** [comment]
fixed!
