### ISSUE TITLE
Potions are slow

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-Global#15]
If you buy potions and hold down the hotkey its very slow.

**Comment by EnzzoCaaue** [comment]
Go to \data\actions\scripts\other\potions.lua and find this line

`exhaust:setParameter(CONDITION_PARAM_TICKS, (configManager.getNumber(configKeys.EX_ACTIONS_DELAY_INTERVAL) - 100))`
change 100 to any value that you like.
