### ISSUE TITLE
Strange Pipe causes debug.

### ISSUE THREAD

**Issue by vomar** [malucooo/Otxserver-Global#17]
Strange pipe outfit is correct but causes debug.
/goto strange pipe

**Comment by yakaaz** [comment]
Do this bro

> ﻿<?xml version="1.0" encoding="utf-8"?>
<npc name="Strange Pipe" script="Strange Pipe.lua" walkinterval="0" floorchange="0">
	<health now="100" max="100" />
	<look type="668" head="0" body="0" legs="0" feet="0" addons="0" />
</npc>

**Comment by yakaaz** [comment]
Put 0 in walkinterval

`﻿<?xml version="1.0" encoding="utf-8"?>
<npc name="Strange Pipe" script="Strange Pipe.lua" walkinterval="0" floorchange="0">
	<health now="100" max="100" />
	<look type="668" head="0" body="0" legs="0" feet="0" addons="0" />
</npc>`

**Comment by malucooo** [comment]
thank you boys! nice job!!
