### ISSUE TITLE
Error after kill a monster

### ISSUE THREAD

**Issue by TMPretox** [malucooo/otxserver-global#3]
EDIT : This is after kill monster!
EDIT 2 : How open Tibia 11 with included ip changer 11 ? Installed 11.0 and after run apply crashing .

Lua Script Error: [CreatureScript Interface]
data/creaturescripts/scripts/gnomebase/bossesWarzone.lua:onKill
data/creaturescripts/scripts/gnomebase/bossesWarzone.lua:8: attempt to call method 'getMonster' (a nil value)
stack traceback:
        [C]: in function 'getMonster'
        data/creaturescripts/scripts/gnomebase/bossesWarzone.lua:8: in function <data/creaturescripts/scripts/gnomebase/bossesWarzone.lua:7>

**Comment by Blingx** [comment]
Is this problem occurring on tibia 11 or on all client variations?

**Comment by nikko1337** [comment]
I get the same error on 10.99 so its not client related.

**Comment by TMPretox** [comment]
yep, this error from 10.99

**Comment by nikko1337** [comment]
You can get this error just by leaving the server online for awhile, at least for me. REF: http://www.tibiaking.com/forum/forums/topic/68411-otxserver-1098-11-global-full-otherworld-quests-events-topico-re-ativado-vemcommalucooo/?page=115#comment-445094

**Comment by Tetee11** [comment]
`function Creature.getMonster(self)
    return self:isMonster() and self or nil
end`

add this at the end of global.lua

**Comment by malucooo** [comment]
thank you very much for help the project!
