### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by vomar** [malucooo/Otxserver-Global#30]
http://i.imgur.com/z4cj9Du.gif
http://i.imgur.com/TZ9X1oC.png
09:46 You see an item of type 24731.
Item ID: 24731
Position: 33688, 31742, 8
09:46 You see an item of type 24731.
Item ID: 24731
Position: 33687, 31742, 8
09:46 You see an item of type 24731.
Item ID: 24731
Position: 33686, 31741, 8
09:46 You see an item of type 24731.
Item ID: 24731
Position: 33682, 31741, 8
09:47 You see an item of type 24731.
Item ID: 24731
Position: 33713, 31740, 8
09:47 You see an item of type 24731.
Item ID: 24731
Position: 33711, 31739, 8
09:47 You see an item of type 24731.
Item ID: 24731
Position: 33715, 31719, 8
09:47 You see an item of type 24731.
Item ID: 24731
Position: 33700, 31728, 8
09:47 You see an item of type 24642.
Item ID: 24642
Position: 33684, 31721, 8
09:47 You see a hole. http://i.imgur.com/25h1Im8.gifv
Item ID: 8250
Position: 33659, 31766, 8
09:47 You see a stairs.
Item ID: 24812
Position: 33655, 31765, 8
09:48 You see an item of type 24642.
Item ID: 24642
Position: 33692, 31767, 8
09:48 You see a ground.
Item ID: 25011
Position: 33689, 31734, 7
09:49 You see a dead savage (Vol:15).
Item ID: 24804
Decays to: 24805
Position: 33661, 31737, 7
09:49 You see a dead ogre shaman (Vol:15).
Item ID: 24796
Decays to: 24797
Position: 33671, 31737, 7
09:49 You see a dead ogre shaman (Vol:15).
Item ID: 24796
Decays to: 24797
Position: 33682, 31740, 7
09:49 You see an item of type 25300.                        = should be hole
Item ID: 25300
Position: 33686, 31743, 7
09:49 You see a dead ogre shaman (Vol:15).
Item ID: 24796
Decays to: 24797
Position: 33684, 31743, 7
09:50 You see an item of type 23770.
Item ID: 23770
Position: 33649, 31662, 7
09:50 You see a ventilation grille.
Item ID: 25406
Position: 33657, 31657, 7
09:50 You see an item of type 25052.
Item ID: 25052
Position: 33668, 31619, 7
09:50 You see a brown flask. It is empty.
Item ID: 2015
Position: 33666, 31612, 7
09:50 You see an item of type 25046.
Item ID: 25046
Position: 33668, 31610, 7
09:50 You see a paddle.
Item ID: 3600
Position: 33671, 31606, 7
09:50 You see an item of type 25044.
Item ID: 25044
Position: 33669, 31603, 7
09:51 You see a ground.
Item ID: 25013
Position: 33675, 31601, 7                          =                 omg krailos needs to be fixed

Rathleton

09:55 You see a slime slide. http://i.imgur.com/aaqluCc.gifv
Item ID: 23417
Position: 33651, 31941, 7
09:55 You see a magic forcefield.
Item ID: 1387
Position: 33574, 32034, 12
09:57 You see mud.
Item ID: 15635
Position: 33455, 31946, 12
This area is missing 
http://i.imgur.com/yNEiMTR.png
09:59 You see mud.
Item ID: 11561
Position: 33504, 31923, 12
This area is missing 
http://i.imgur.com/ITetf3q.png
09:59 You see stone floor.
Item ID: 22904
Position: 33525, 31924, 12
http://i.imgur.com/xayYPyj.png

Position: 33600, 31980, 12 http://i.imgur.com/KL8GInT.png
Position: 33638, 31909, 13 http://i.imgur.com/S9nZFZX.png http://i.imgur.com/44Stmka.png http://i.imgur.com/Fqmak3F.png

2 npcs? http://i.imgur.com/QG5VkNn.png

??????????????? http://i.imgur.com/HbxJzxb.png Position: 33692, 32044, 12

Area missing 
Position: 33476, 31929, 13
http://i.imgur.com/P42vio5.png
http://i.imgur.com/zh4sXDg.png
Position: 33450, 31929, 13
You need to fix this spawn.

Entire spawn is fucked.
Position: 33539, 32047, 13
http://i.imgur.com/qIz6tRq.png
Position: 33531, 32026, 13
http://i.imgur.com/XPpF9x4.png

wtf?
http://i.imgur.com/XjOyHxS.gif

Map is moved by 1 sqm
http://i.imgur.com/lre1QHW.gif

**Comment by murilao** [comment]
All was corrected.
