### ISSUE TITLE
Drowning bug

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-Global#31]
The drowning condition not dissapear later of step in or step out in few floors ,under water.

This only dissapear when player logout, but if the player have pk, so this become infinite.

http://imgur.com/a/6esQo

**Comment by murilao** [comment]
was fixed. Thank you for report bug

**Comment by darkjav** [comment]
@malucooo  @murilao 

Really this fix the drowning?, excuse me, but this not is true, i have this file identical:

https://www.diffchecker.com/Gfns8UHo

I think that problem is also in movements.xml, on this lines:

`	<movevent event="StepIn" fromid="5405" toid="5410" script="drowning.lua" />
	<movevent event="StepOut" fromid="5405" toid="5410" script="drowning.lua" />
	<movevent event="StepIn" fromid="23944" toid="23949" script="drowning.lua" />
	<movevent event="StepOut" fromid="23944" toid="23949" script="drowning.lua" />
	<movevent event="StepIn" itemid="10019" script="drowning.lua" />
	<movevent event="StepOut" itemid="10019" script="drowning.lua" />`

Please you can check again? I try to fix adding more type items of floor, but not possible.

**Comment by murilao** [comment]
is fixed

**Comment by darkjav** [comment]
Maybe the problem is in Sea Serpent Area, Svargrond, because there exist teleports that not check the drowning condition when you get out teleported of there.

Is necessary remove the condition when the player stepIn a teleport and get teleported right?

We need use "if" statement to check if have the teleport or not
something like this:

`if Tile(item:getPosition()):getItemById(1387) then
        player:removeCondition(CONDITION_DROWN)
        return true
    end`

Also we can just check the position, but we can be more smart and check the teleports.
I hope that together can solved this. Thanks.
