### ISSUE TITLE
Can you add website files?

### ISSUE THREAD

**Issue by jerryb1988** [malucooo/otxserver-global#4]
I see it uses AAC and database tables are added to SQL but no www files are included. Can you add them for next release so all website functions work?

**Comment by lamonato29** [comment]
you can find the site here..
https://github.com/gesior/Gesior2012/tree/TFS-1.0

**Comment by jerryb1988** [comment]
I see your database has z_network_box z_news_ticker z_polls z_polls_answers z_shopguild and the default website doesnt? Or do I just not see it?

**Comment by lamonato29** [comment]
sorry i dont understand

**Comment by jerryb1988** [comment]
that github doesnt have polls, news ticker, guild shop. you add those extra?

**Comment by lamonato29** [comment]
srry bro im not the manager of this repository.. just sent the link ;D

**Comment by malucooo** [comment]
i'm not a webdesigner =/
