### ISSUE TITLE
"spawntime can not be less than 1 seconds."

### ISSUE THREAD

**Issue by VonGrzesieK** [malucooo/Otxserver-Global#41]
Como eu não consigo abrir um Pull requests, vai por aqui mesmo.

[Warning - Spawns::loadFromXml] Priestess **( 33165 / 31645 / 013 )** spawntime can not be less than 1 seconds.

**global-spawn.xml**
**Linha 112293** (monster name="Priestess" x="0" y="-3" z="13" spawntime=**"0"** )

**Comment by Andreeyyy** [comment]
Corrigindo

**Comment by Andreeyyy** [comment]
Testa la pra gente

**Comment by VonGrzesieK** [comment]
Tudo nos conformes!
Obrigado.
