### ISSUE TITLE
ferumbras quest esta pronta, so falta reupar o mapa msg me

### ISSUE THREAD

**Issue by xxtsam** [malucooo/Otxserver-Global#44]
alguem tem ou saberia me passar o script ao passar em um determinado teleport adicionar um valor
por exemplo:
player:getStorageValue( xxx) 

so falta isso pra liberar a feru quest

**Comment by EnzzoCaaue** [comment]
Malucoo respondeu no tópico lá no tibiaking, 
set > adiciona
get > pega
player:getStorageValue(xxx) 
player:setStorageValue(xxx)

**Comment by xxtsam** [comment]
sim, eu vi
mas preciso do "set" do inicio ao fim só pra mudar o StorageValue

**Comment by EnzzoCaaue** [comment]
Não entendi..

**Comment by xxtsam** [comment]
estou com o fix da feru quest, precisa reupar o mapa que consertei alguns lugares e adicionar um monstro

**Comment by murilao** [comment]
Me passe o mapa, para eu verificar e upar.
