### ISSUE TITLE
10.98 crash client

### ISSUE THREAD

**Issue by kito2** [malucooo/Otxserver-Global#59]
https://github.com/malucooo/Otxserver-Global/commit/fb366931ff3585fc73f62ff3c06637b08e6d4617
https://github.com/malucooo/Otxserver-Global/commit/a6d9fbc2f814d9fc0562f7ced9dc214e22818926

By adding those and also

Updating outfits.xml and mounts.xml

The client crashed at login (10.98)

If using another client like 10.96 no crash, until you try to select outfit/mount.

**Comment by murilao** [comment]
Windows or Linux?

**Comment by kito2** [comment]
Windows.

PS: Using TFS 1.2 official, just added the 10.98 changes you have done here that I have seen. Maybe there are some "hidden" commits which doesn't talk about 10.98 and I missed them. Could this be?

**Comment by murilao** [comment]
Well, is not giving debug.
