### ISSUE TITLE
Missing "archive.dll"

### ISSUE THREAD

**Issue by Maldero** [malucooo/Otxserver-Global#6]
Missing dll archive.dll for windows.

[archive.zip](https://github.com/malucooo/Otxserver-Global/files/470886/archive.zip)

**Comment by malandriso** [comment]
![aaaaaaa](https://cloud.githubusercontent.com/assets/5194771/18495218/33a43858-79ea-11e6-9723-43a0132940d4.png)

**Comment by Marcelo-Petrucelli** [comment]
Please, create a pull request, I haven't seen this as a missing file, I'll check and come back to close this issue or add it to the project and link it here.

**Comment by Marcelo-Petrucelli** [comment]
Ok, I just checked with other developers, in fact I think that those Dlls should come with windows or be 3rd part. The github is only for our development of the project. We're studying the creation of releases and we can embed all necessary Dlls for windows on the Windows Release.

We'll probably just do the same for Linux if it has necessary dependencies.

I recommend you use Windows 8.1 or 10.

**Comment by Marcelo-Petrucelli** [comment]
Solved on ee501f7deee85d7e91bdb63f553227c8b75619ab
