### ISSUE TITLE
Unstable Tunnel

### ISSUE THREAD

**Issue by kito2** [malucooo/Otxserver-Global#60]
Can someone add this one, can't find anywhere...

Neither their looktype.

**Comment by murilao** [comment]
I did not understand, has more detail?

**Comment by murilao** [comment]
speaking of monster?

**Comment by kito2** [comment]
AH ok..


https://www.youtube.com/watch?v=8MAhr7Fa-pI check the video at that invasion 📦 
http://tibia.wikia.com/wiki/Unstable_Tunnel
