### ISSUE TITLE
NPC System

### ISSUE THREAD

**Issue by yakaaz** [malucooo/Otxserver-Global#72]
Hello bros, maybe we have problem with all npcs because when do you talk o speak with they, the conversartion turns too slow, i mean they have a delay , example if u say hi , the npc wait a long time maybe 3 o 2 secs and then he responses

**Comment by darkjav** [comment]
In this line:
https://github.com/malucooo/Otxserver-Global/blob/master/data/npc/lib/npcsystem/npchandler.lua#L74

Put:
talkDelayTime = 1,

:smiley:
