### ISSUE TITLE
AUTHENTICATOR_DIGITS 

### ISSUE THREAD

**Issue by kito2** [malucooo/Otxserver-Global#74]
https://github.com/malucooo/Otxserver-Global/blob/cb5f6a262e4185458ade6349daa9e7e9448c73b4/src/tools.cpp#L227-L232

Hey I was looking at sources found this authentificator code... How to enable this? Searched at configmanager but nothing, also added a seed to 'secret' column at table players but nothing.

Could you explain?

**Comment by darkjav** [comment]
Guide here:

https://github.com/otland/forgottenserver/pull/1603#issuecomment-212450549

:smiley:
