### ISSUE TITLE
AUTHENTICATOR_DIGITS 

### ISSUE THREAD

**Issue by kito2** [malucooo/Otxserver-Global#75]
https://github.com/malucooo/Otxserver-Global/blob/master/src/definitions.h#L35-L36

I can't make it work... Added the secret code generated by google. When log in it is not asking for the authentificator code.

**Comment by darkjav** [comment]
This not work, because only working without cast system, only that you replace with the next code:

Guide here:
otland/forgottenserver#1603 (comment)

But not work with cast system, so you need choice what is more important for you.

**Comment by kito2** [comment]
Thanks for the information bro... So in order to active this feature, what you have to disable from Malucoo src? Would appreciate that information.

**Comment by darkjav** [comment]
Here:
https://github.com/otland/forgottenserver/pull/1603/files

Only you need do the changes of protocollogin.cpp and protocollogin.h

**Comment by kito2** [comment]
Thanks.... Yeah, did that but still crashing. How to disable Cast System?

**Comment by darkjav** [comment]
in config.lua try:

enableLiveCasting = false

**Comment by kito2** [comment]
Thanks, this should be marked as solved.
