### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by vomar** [malucooo/Otxserver-Global#8]
Debug Assertion 10.97 Objects.cpp 640
Tue Sep 13 15:59:24 2016
Graphic Engine: DirectX9 (2)
Operating System: Windows 7 Ultimate Edition 64 Bit in POL
Processor: AMD Phenom II X4 960
Video Card: ATI Radeon HD AMD 6700 
Last Packet Types: 107 160 160 147 029 030 109 106 109 109
Last Packet: 107 146 126 157 125 011 002 000 000 255 000 000 000 000 000 000
Player Position: [32399,32155,11]
Player Name: Player (Astera)
Player Action: 048 046 048 046 048 046 048 058 055 049 055 050
Player.cpp 344: exception occurred, reason:
Network.cpp 855: exception occurred, reason:
Control.cpp 1525: exception occurred (Type = 107) (MainWindow = 03AAA7A8), reason:
Communication.cpp 2625: exception occurred (rx = 11) (ry = 8), reason:
Objects.cpp 643: exception occurred (Type = 0) (Flag = 10), reason:
Objects.cpp 640: assertion failed (Type = 0) (ObjectProperties->high() = 23725), reason:
In(Type,ObjectProperties->low(),ObjectProperties->high())
Comment:

**Comment by Marcelo-Petrucelli** [comment]
Olá vomar,

Você poderia seguir nossas recomendações e editar sua Issue? Precisamos saber como conseguiu esse erro e outras informações pertinentes. por favor, verifique o seguinte Link:

https://github.com/malucooo/Otxserver-Global/wiki/Issues
