### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by mattyx14** [malucooo/Otxserver-Global#9]
Upload the map ... are bugged

**Comment by Maldero** [comment]
It's here: https://github.com/malucooo/Otxserver-Global/raw/master/data/world/global.otbm
But still in zip is bugged (1kb).

**Comment by Marcelo-Petrucelli** [comment]
No, just use Git-Lfs, we have a Tutorial at: https://github.com/malucooo/Otxserver-Global/wiki/Git-e-Git-Lfs

Closed.
